/* Crea Tabla Usuarios*/ 
CREATE TABLE "SYSTEM"."USUARIOS" 
   (	"ID" NUMBER(9,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FECHANAC" DATE NOT NULL ENABLE, 
	"RUNUSUARIO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

/* Crea Tabla Capacitacion*/ 
 CREATE TABLE "SYSTEM"."CAPACITACION" 
   (	"IDCAPACITACION" NUMBER(9,0), 
	"CAPFECHA" DATE NOT NULL ENABLE, 
	"CAPHORA" DATE, 
	"CAPLUGAR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CAPDURACION" NUMBER(4,0), 
	"CLIENTE_RUTCLIENTE" NUMBER(9,0), 
	 PRIMARY KEY ("IDCAPACITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("IDCAPACITACION")
	  REFERENCES "SYSTEM"."CLIENTE" ("IDCLIENTE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


/* Crea Tabla Pago*/ 
 CREATE TABLE "SYSTEM"."PAGO" 
   (	"IDPAGO" NUMBER NOT NULL ENABLE, 
	"MESPAGO" VARCHAR2(20 BYTE), 
	"ANOPAGO" VARCHAR2(20 BYTE), 
	"RUTCLIENTE" VARCHAR2(10 BYTE), 
	"NOMBRECLIENTE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PAGO_PK" PRIMARY KEY ("IDPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

/* Crea Tabla Visita*/ 

CREATE TABLE "SYSTEM"."VISITA" 
   (	"IDVISITA" NUMBER(9,0), 
	"HORAVISITA" NVARCHAR2(20) NOT NULL ENABLE, 
	"FECHAVISITA" VARCHAR2(20 BYTE), 
	"VISLUGAR" NUMBER NOT NULL ENABLE, 
	"VISCOMENTARIOS" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"CLIENTE_RUTCLIENTE" NUMBER(9,0), 
	 PRIMARY KEY ("IDVISITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("IDVISITA")
	  REFERENCES "SYSTEM"."CLIENTE" ("IDCLIENTE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE TABLE users (username VARCHAR2(20) not null enable,
password VARCHAR2(100),
rol VARCHAR2(20),
constraint users_pk primary key (username));

INSERT INTO users (username, password, rol) VALUES ('pinguino', '$2a$10$H4Pc1lcuKP6kwko9fqkdkehXSZZryCswWzCjpxsCiN7sJtLP.CdyK', 'cliente');

INSERT INTO users (username, password, rol) VALUES ('juanito', '$2a$10$sBgT14Z.82rClCdfm2A69eVLcyu/EhioTJoSJlspoYux4QTGXhY8C', 'admin');

INSERT INTO users (username, password, rol) VALUES ('Miguelito', '$2a$10$1orgSholO5sfFQSNRBcSQuNT02wZ97eeEWyFa2Zv1oMzDiwE1JqZm', 'profe');